# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:

  matrix:
    - PYTHON: "C:\\Python310-x64"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python35-x64"

cache:
  ## Cache swig, which we install via AppVeyor.
  # The syntax here is <dir-to-cache> -> <invalidated-when-this-file-changes>
  # If the appveyor.yml script is changed, then the cache is invalidated.
  # https://www.appveyor.com/docs/build-cache/
  - C:\ProgramData\chocolatey\bin -> appveyor.yml # swig.exe
  - C:\ProgramData\chocolatey\lib -> appveyor.yml # supporting swig Lib files.

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;c:\\SoftHSM2\\bin;c:\\SoftHSM2\\lib"
  - "SET SOFTHSM2_CONF=C:\\SoftHSM2\\etc\\softhsm2.conf"
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
  - test\appveyor_install.cmd

build_script:
  - python setup.py sdist
  - python setup.py bdist
  - python setup.py bdist_wininst
  - python setup.py bdist_msi
  - python setup.py bdist_wheel
  - python setup.py install
  - copy /Y src\LowLevel.py PyKCS11\
  - pip show PyKCS11 | python -c "import sys; print([line for line in sys.stdin if line.startswith('Location:')][0].split(':',1)[1].strip())" > _tmp
  - set /p PYKCS11_INSTALL_DIR=<_tmp
  - copy /Y %PYKCS11_INSTALL_DIR%\PyKCS11\* PyKCS11\
  - del _tmp

test_script:
  - python run_test.py

artifacts:
  - path: dist/*
    name: PythonPackages
